image:
  - Visual Studio 2019
  - Visual Studio 2017

platform:
  - x64
  - x32

configuration:
  - Release

build_script:
  - dir "C:/local"
  - cd ../yas/tests/base
  - echo Build for %platform%-%configuration%
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config %configuration%
  - Release\yas-base-test.exe binary
