image:
  - Visual Studio 2019
  - Visual Studio 2017

platform:
  - x64
  - x32

configuration:
  - Release

environment:
  BOOST_ROOT: C:\local\boost_1_66_0

cache:
  - c:\local\boost_1_66_0

install:
  - ps: Write-Host "Checking for Boost 1.66.0 x86...";$boostdir  = Test-Path $Env:BOOST_ROOT;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.66.0 x86...";$exePath = "$Env:TEMP\boost_1_66_0-msvc-14.1-32.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.66.0%2Fbinaries%2Fboost_1_66_0-msvc-14.1-32.exe', $exePath);Write-Host "Installing Boost 1.66.0 x86...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.66.0 x86 installed!" -ForegroundColor Green
  - ps: Write-Host "Checking for Boost 1.66.0 x86-64...";$boostdir  = Test-Path $Env:BOOST_ROOT;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.66.0 x86-64...";$exePath = "$Env:TEMP\boost_1_66_0-msvc-14.1-64.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.66.0%2Fbinaries%2Fboost_1_66_0-msvc-14.1-64.exe', $exePath);Write-Host "Installing Boost 1.66.0 x86-64...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.66.0 x86-64 installed!" -ForegroundColor Green

build_script:
  - dir "C:/local/boost_1_66_0"
  - cd ../yas/tests/base
  - echo Build for %platform%-%configuration%
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config %configuration%
  - Release\yas-base-test.exe binary
