image:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64
  - x32

configuration:
  - Release

build_script:
#  - dir "C:\Libraries\boost_1_66_0"
  - cd ../yas/tests/base
  - echo Build for %platform%-%configuration%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x32,x64 ..
  - cmake --build . --config %configuration%
  - Release\yas-base-test.exe binary
