language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - wget http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.bz2
  - tar jxf boost_1_64_0.tar.bz2
  - cp -r boost_1_64_0/boost /usr/local/include

install:
  - g++ --version
  - cmake --version

before_script:
   - cd $TRAVIS_BUILD_DIR/tests/base
   - mkdir build
   - cd build
   - cmake -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
   - cd $TRAVIS_BUILD_DIR/tests/base/build
   - cmake --build . --config $CONFIG
   - ./yas-base-test binary
