language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libboost-all-dev

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.9 clang-3.8 -y
  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++
  - sudo cp /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo cp /usr/bin/g++-4.9 /usr/bin/g++
  - sudo cp /usr/bin/clang-3.8 /usr/bin/clang
  - sudo cp /usr/bin/clang++-3.8 /usr/bin/clang++
#  - find /usr/include -maxdepth 1 -name '*' -type d | sort
#  - wget http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.bz2
#  - tar jxf boost_1_64_0.tar.bz2
#  - cp -r boost_1_64_0/boost /usr/local/include

install:
  - g++ --version
  - clang++ --version
  - cmake --version

before_script:
  - cd $TRAVIS_BUILD_DIR/tests/base
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
  - cd $TRAVIS_BUILD_DIR/tests/base/build
  - cmake --build . --config $CONFIG
  - ./yas-base-test binary
