
// Copyright (c) 2010-2023 niXman (github dot nixman at pm dot me). All
// rights reserved.
//
// This file is part of YAS(https://github.com/niXman/yas) project.
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef __yas__boost_types_hpp
#define __yas__boost_types_hpp

#if defined(YAS_SERIALIZE_BOOST_TYPES)

#include "types/boost/array.hpp"
#include "types/boost/chrono.hpp"
#include "types/boost/container_deque.hpp"
#include "types/boost/container_flat_map.hpp"
#include "types/boost/container_flat_multimap.hpp"
#include "types/boost/container_flat_set.hpp"
#include "types/boost/container_flat_multiset.hpp"
#include "types/boost/container_list.hpp"
#include "types/boost/container_map.hpp"
#include "types/boost/container_multimap.hpp"
#include "types/boost/container_multiset.hpp"
#include "types/boost/container_set.hpp"
#include "types/boost/container_slist.hpp"
#include "types/boost/container_stable_vector.hpp"
#include "types/boost/container_static_vector.hpp"
#include "types/boost/container_string.hpp"
#include "types/boost/container_vector.hpp"
#include "types/boost/container_wstring.hpp"
#include "types/boost/fusion_list.hpp"
#include "types/boost/fusion_map.hpp"
#include "types/boost/fusion_pair.hpp"
#include "types/boost/fusion_set.hpp"
#include "types/boost/fusion_tuple.hpp"
#include "types/boost/fusion_vector.hpp"
#include "types/boost/optional.hpp"
#include "types/boost/string_view.hpp"
#include "types/boost/tuple.hpp"
#include "types/boost/variant.hpp"
#include "types/boost/unordered_set.hpp"
#include "types/boost/unordered_map.hpp"
#include "types/boost/unordered_multimap.hpp"
#include "types/boost/unordered_multiset.hpp"

#endif // defined(YAS_SERIALIZE_BOOST_TYPES)

#endif // __yas__boost_types_hpp
